### ISSUE TITLE
Lots of useless rerenders in BottomNavigation

### ISSUE THREAD

**Issue by vlad-zhukov** [winoteam/react-router-navigation#29] opened 2017-07-27 10:32 UTC
Every route change causes multiple (3-4) renders in a row for each mounted tab (I use the lazy mode) in BottomNavigation, including inactive ones. Needless to say it causes major performance problems.

Currently I use a little workaround when render each tab:

```js
export default ({match, history, path}) => {
  if (match == null || !history.location.pathname.startsWith(path)) return null;
  return (
    <Navigation>
      // ...
    </Navigation>
  );
};
```

However I believe the issue is most likely goes down deeper to excessive History rerenders. Can something be done about it?

**Comment by n1ru4l** [comment] 2017-08-01 09:06
Possible duplicate of https://github.com/LeoLeBras/react-router-navigation/issues/12

**Comment by LeoLeBras** [comment] 2017-09-06 08:26
Hey @vlad-zhukov,
> It's good idea move each route to a separate component if they don't depend on the index, and apply shouldComponentUpdate to prevent unnecessary re-renders. ([source](https://github.com/react-native-community/react-native-tab-view#user-content-avoid-unnecessary-re-renders))

`<BottomNavigation />` depends on package `react-native-tab-view`. So it's difficult to improve performance. 
`<History />` causes some performance issues. I will refactor this component for next release.

**Closed** 2021-06-26 15:17 UTC
Labels: help wanted 🖐, performance :rocket:
